# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBu1BZ5tKJDlWd4s57_t0U1jbxF2EaCS
"""

pip install streamlit

import streamlit as st

def largest_of_three_numbers(a, b, c):
    """
    This function takes three numbers as input and returns the largest of the three.
    """
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c

st.title("Find the largest among the 3 given numbers")

a = st.number_input("Enter the first number:")
b = st.number_input("Enter the second number:")
c = st.number_input("Enter the third number:")

if st.button("Find the largest"):
    result = largest_of_three_numbers(a, b, c)
    st.success(f"The largest number is {result}.")

